### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by joe-bell** [joe-bell/raam#3]
- [x] Add Box
- [x] Add Intro (OOCSS, `o-layout`, aknowledgements, justificiation for separate components)
- [x] Update heading styling
- [x] Update inline code styling
- [x] Maybe dynamically load react previews?
- [x] Bump to minor version and publish
- [x] Add site footer
